apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp2
  labels:
    app: mywebapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp2
  template:
    metadata:
      labels:
        app: mywebapp2
    spec:
      containers:
      - name: mywebapp2
        image: poornimaasundkar/python_mywebapp2
        ports:
        - containerPort: 5000
